dressCode/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('codeforgood.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

codeforgood/models.py
from django.db import models
from django.utils import timezone


def upload_to(instance, filename):
    return "%s"%filename

class NewsArticle(models.Model):
    title = models.CharField(max_length=30)
    url = models.CharField(max_length=300)
    picture = models.ImageField(upload_to=upload_to, blank=True)
    description = models.CharField(max_length=160)
    views = models.IntegerField(default=0)
    date = models.DateTimeField(default=timezone.now)


class RoleModel(models.Model):
    name = models.CharField(max_length=70)
    title = models.CharField(max_length=60)
    picture = models.ImageField()
    gender = models.CharField(max_length=30)
    ethnicity = models.CharField(max_length=30)
    position = models.CharField(max_length=30)
    description = models.CharField(max_length=160)
    url = models.CharField(max_length=300)


class VideoArticle(models.Model):
    title = models.CharField(max_length=30)
    description = models.CharField(max_length=160)
    url = models.CharField(max_length=300)
    views = models.IntegerField()


class VisitedPagesCounter(models.Model):
    # Each field represents the view count for a specific page
    # (ie. home_views = Index Page views)
    home_views = models.IntegerField(default=0)
    careers_views = models.IntegerField(default=0)
    contact_views = models.IntegerField(default=0)
    meet_your_hero_views = models.IntegerField(default=0)
    news_views = models.IntegerField(default=0)
    videos_views = models.IntegerField(default=0)
    play_views = models.IntegerField(default=0)
    future_self_views = models.IntegerField(default=0)


class FutureSelfRequest(models.Model):
    story = models.CharField(max_length=350)
    email = models.CharField(max_length=60)

templates/add_news_article.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Add new article
{% endblock %}

{% block main %}
    {% if message %}
        <div class="row justify-content-center">
            <div class="btn alert-success mt-0">{{ message }}</div>
        </div>
    {% endif %}
    <div class="text-center margin-top-50 mb-3">
        <h2 class="text-info dresscode-font">Add a new Article!</h2>
        <h5 class="text-dark mt-4 dresscode-font-italic">(This feature is only available to admins)</h5>


        {% if form %}
            <form id="add_news_article" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="form-group mt-4">
            <label for="id_story">Enter the title:</label>
            <input required type="text" class="form-control container" id="id_title" name="title" rows="3">
        </div>
                <div class="form-group mt-4">
            <label for="id_url">Enter the article's URL:</label>
            <input required type="url" class="form-control container" id="id_url" name="url" rows="3">
        </div>
                <div class="form-group mt-4 file-upload">
            <label for="id_picture">Upload picture:</label>
            <input required type="file" class="form-control container" id="id_picture" name="picture" rows="3">
        </div>
                <div class="form-group mt-4">
            <label for="id_description">Article text:</label>
            <textarea required class="form-control container" id="id_description" name="description" rows="3"></textarea>
        </div>
        <p class="text-dark mt-4 container"><button type="submit" value="Submit"  class="btn btn-success">Submit</button></p>
        </form>
            
        {% endif %}

    </div>

<div class="container margin-top-20" style="margin-bottom: 200px"></div>


{% endblock %}

templates/admin_site.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
Administration
{% endblock %}

{% block main %}
<div id="container" data-url="{% url 'chart_data' %}"></div>
<script src="https://code.highcharts.com/highcharts.src.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $.ajax({
      url: $("#container").attr("data-url"),
      dataType: 'json',
      success: function (data) {
        Highcharts.chart("container", data);
      }
    });

</script>
<div class="text-center dresscode-font"><h3 >Most viewed Videos</h3></div>
<div class="container">
    <table class="table table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">Video ID</th>
            <th scope="col">Title</th>
            <th scope="col">Views from website</th>
            <th scope="col">View/Visit Ratio (%)</th>
        </tr>
        </thead>
        <tbody>
        {% for video,ratio in videos %}
        <tr>
            <th scope="row">{{video.pk}}</th>
            <td>{{video.title}}</td>
            <td>{{video.views}}</td>
            <td>{{ratio}}%</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<div class="text-center dresscode-font"><h3 >Most viewed News Articles</h3></div>
<div class="container">
    <table class="table table-hover table-dark">
        <thead>
        <tr>
            <th scope="col">News Article ID</th>
            <th scope="col">Title</th>
            <th scope="col">Views from website</th>
            <th scope="col">View/Visit Ratio (%)</th>
        </tr>
        </thead>
        <tbody>
        {% for article,ratio in news_articles %}
        <tr>
            <th scope="row">{{article.pk}}</th>
            <td>{{article.title}}</td>
            <td>{{article.views}}</td>
            <td>{{ratio}}%</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            dressCode
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/styleaddons.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">
    <link rel="stylesheet" href="{% static 'assets/fonts/ionicons.min.css' %}">
    <link rel="shortcut icon" href="{% static 'logo_icon.ico' %}">
    {% block head %}
    {% endblock %}
</head>

<body>
<nav class="navbar navbar-dark navbar-expand-lg fixed-top bg-white portfolio-navbar purple-gradient">
    <div class="container">
        <a class="navbar-brand logo" href="{% url 'index' %}">
            <img class="d-xs-block d-sm-block d-md-none d-lg-none d-xl-none ml-3" style="height: 50px" src="{% static 'dressCODE_mobile.png' %}">
            <img class="d-none d-sm-none d-md-block d-lg-block d-xl-block w-50" src="{% static 'dressCODE_Final.png' %}">
        </a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav"><span class="sr-only">Toggle navigation</span><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse"
             id="navbarNav">
            <ul class="nav navbar-nav ml-auto">
                <li class="nav-item dresscode-font" role="presentation"><a class="nav-link" href="{% url 'news' %}">News</a></li>
                <li class="nav-item dresscode-font" role="presentation"><a class="nav-link" href="{% url 'meet_your_hero' %}">Role Model</a></li>
                <li class="nav-item dresscode-font" role="presentation"><a class="nav-link" href="{% url 'future_self' %}">Future Self</a></li>
                <li class="nav-item dresscode-font" role="presentation"><a class="nav-link" href="{% url 'videos' %}">Videos</a></li>
                <li class="nav-item dresscode-font" role="presentation"><a class="nav-link" href="{% url 'play' %}">Game</a></li>
            </ul>
        </div>
    </div>
</nav>
<main class="page lanidng-page">
    {% block main %}

    {% endblock %}
</main>
<footer class="page-footer bg-light dresscode-font">
    <div class="container">
        <div class="links"><a href="https://dresscode.org.uk/">About DressCode</a>
            <a href="https://dresscode.org.uk/get-with-the-program/">Contact us</a>
            <a href="https://dresscode.org.uk/what-we-do/">What we do</a>

            <!-- Only the admins will see these links -->
            {% if user.is_authenticated %}
            <a href="{% url 'admin_site' %}">Admin</a>
            <a href="{% url 'add_news_article' %}">Add Article</a>
            {% endif %}
        </div>
        
        
        <div class="social-icons"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i
                class="icon ion-social-instagram-outline"></i></a><a href="#"><i
                class="icon ion-social-twitter"></i></a></div>
    </div>
    <img src="{% static 'dressCODE_Final_black.png'%}" style="width: 120px; margin: -5px 0px 20px 0px;">
</footer>

<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/codeforgood.js' %}"></script>
</body>

</html>

templates/careers.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Careers
{% endblock %}

{% block main %}

{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Contact Us
{% endblock %}

{% block main %}

{% endblock %}

templates/display_future.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    News
{% endblock %}

{% block main %}
    <div class="text-center margin-top-50 mb-3 marg">
        <h2 class="text-info dresscode-font">Future self Admin panel!</h2>
    </div>
    <br>
    <div class="container margin-top-20">

    {% if display_future %}
        {% for future in display_future %}
                <div class="row margin-top-10 justify-content-center">
                    <div class="text-box text-box-mobile col-md-8">
                        <div class="row">
                            <span><strong>Title: </strong>{{future.email}}</span>
                        </div>
                        <div class="row">
                            <span><strong>Description: </strong>{{future.story}}</span>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
    {% else %}
        There no futures!
    {% endif %}
{% endblock %}

templates/future_self.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Meet your HERO!
{% endblock %}

{% block main %}
    {% if message %}
        <div class="row justify-content-center">
            <div class="btn alert-success mt-0">{{ message }}</div>
        </div>
    {% endif %}
    <div class="text-center margin-top-50 mb-3">
        <h2 class="text-info dresscode-font">Ask your future self!</h2>
        <h5 class="text-dark mt-4 dresscode-font-italic">Tell us a bit more about you, where you come from, your tech aspirations and what do you look forward to in the future.</h5>
        <h5 class="text-dark mt-4 container">We will then match you with one of our experts from our network that has had a similar upbringing as you. You will then be able to ask them questions, learn about their story and use it as a blueprint to create yours!</h5>
        <form action = "{% url 'future_self' %}" method = "post">{% csrf_token %}
        <div class="form-group mt-4">
            <label for="id_story">Share your story here:</label>
            <textarea class="form-control container" id="id_story" name="story" rows="3"></textarea>
        </div>
        <div class="form-group">
            <label for="id_email">Email address:</label>
            <input name="email" type="email" class="form-control container" id="id_email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll only share your email address with your future mentor.</small>
        </div>
        <p class="text-dark mt-4 container"><button type="submit" value="Submit"  class="btn btn-success">Submit</button></p>
        </form>
        
    </div>

<div class="container margin-top-20" style="margin-bottom: 200px"></div>


{% endblock %}

templates/game.html
{% extends 'base.html' %}}
{% load staticfiles %}

{% block head %}
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Unity WebGL Player | JPMC dressCode game 2019</title>
    <link rel="shortcut icon" href="{% static 'TemplateData/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'TemplateData/style.css' %}">
    <script src="{% static 'TemplateData/UnityProgress.js' %}"></script>
    <script src="{% static 'Build/UnityLoader.js' %}"></script>
    <script>
      var unityInstance = UnityLoader.instantiate("unityContainer", "{% static 'Build/Build3.json' %}", {onProgress: UnityProgress});
    </script>
{% endblock %}

{% block main %}
<div class="game" style="height: 500px">
    <div class="webgl-content">
      <div id="unityContainer" style="width: 960px; height: 600px"></div>
      <div class="footer">
        <div class="webgl-logo"></div>
        <div class="fullscreen" onclick="unityInstance.SetFullscreen(1)"></div>
        <div class="title">JPMC dressCode game 2019</div>
      </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Home
{% endblock %}

{% block main %}
    <section class="clean-block features">
        <div class="container">
            <div class="text-center margin-top-50 mb-5">
                <h2 class="text-info dresscode-font">Reasons to get into Computing Science?</h2>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-5 mb-5">
                    <h4>Salary</h4>
                    <p>The average salary for Computer Science graduates in the UK varies between £42,500 to £72,500.
                    <a href="https://www.cwjobs.co.uk/salary-checker/average-computer-science-salary">Read more.</a></p>
                </div>
                <div class="col-md-5 mb-5">
                    <h4>Life-time Skills</h4>
                    <p>Skills like <b>problem solving</b>, <b>critical thinking</b> and <b>team-working</b> are very useful in society.</p>
                </div>
                <div class="col-md-5 mb-5">
                    <h4>Job Oportunities</h4>
                    <p>Based on LinkedIn there are more than <b>17,000</b> job positions only in the UK. <a href="https://www.linkedin.com/jobs/search/?geoId=101165590&keywords=information%20technology&location=United%20Kingdom">Read more.</a></p>
                </div>
                <div class="col-md-5 mb-5">
                    <h4>Used Everywhere</h4>
                    <p>Computer Science can be combined with any other profession. Finance, Arts, Biology, Agriculture...</p>
                </div>
            </div>
        </div>
    </section>
    <section class="portfolio-block call-to-action border-bottom">
        <div class="container">
            <div class="d-flex justify-content-center align-items-center content">
                <h3 class="dresscode-font">Not convinced?</h3>
                <a class="btn dresscode-button btn-lg dresscode-font-italic" href="{% url 'meet_your_hero' %}">Click Here</a>
            </div>
        </div>
    </section>
    <div class="embed-responsive embed-responsive-16by9">
        <iframe src="https://www.youtube.com/embed/nKIu9yen5nc" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
    </div>
{% endblock %}

templates/meet_your_hero.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Meet your HERO!
{% endblock %}

{% block main %}
    <div class="text-center margin-top-50 mb-3">
        <h2 class="text-info dresscode-font">IT is truly for everyone!</h2>
        <h5 class="text-dark mt-4 dresscode-font-italic">In fact, there is someone just like you excelling in the industry right now.</h5>
    </div>
    <form class="text-center" action="" method="post">{% csrf_token %}
        {{ form.as_table }}
        <button class="btn dresscode-button dresscode-font-italic" type="submit" value="Submit">Submit</button>
    </form>

    <div class="container margin-top-20" style="margin-bottom: 200px">

        {% if rolemodels %}
            {% for rolemodel in rolemodels %}
                <div class="row margin-top-10">
                    <div class="col-md-4">
                        <div class="text-center">
                            <div>
                                <a href="#"><img src="{{ rolemodel.picture.url }}"
                                                 class="height-200 width-200 photo-fit-mobile round-edges-circle"
                                                 alt="item image"></a>
                            </div>
                        </div>
                    </div>
                    <div class="text-box text-box-mobile col-md-8 text-justify">
                        <div>
                            <span><strong>Name: </strong>{{ rolemodel.name }}</span>
                        </div>
                        <div>
                            {% if rolemodel.description|length > 230 %}
                                <span><strong>Description: </strong>{{ rolemodel.description|slice:"0:230" }}...</span>
                            {% else %}
                                <span><strong>Description: </strong>{{ rolemodel.description }}</span>
                            {% endif %}
                        </div>
                        <div>
                            <span><strong>Gender: </strong>{{ rolemodel.gender }}</span>
                        </div>
                        <div>
                            <span><strong>Ethnicity: </strong>{{ rolemodel.ethnicity }}</span>
                        </div>
                        <div>
                            <span><strong>Position: </strong>{{ rolemodel.position }}</span>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        {% endif %}
{% endblock %}

templates/news.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    News
{% endblock %}

{% block main %}
    <div class="text-center margin-top-50 mb-3">
        <h2 class="text-info dresscode-font">Happening in tech right now!</h2>
    </div>
    <br>
    <div class="container margin-top-20">

{% if news_articles %}
           {% for news in news_articles %}
                <div class="row margin-top-10">
                    <div class="col-md-3">
                        <div class="text-center">
                            <div>
                                <a target="_blank" href="{{ news.url }}"><img onclick="increment_article_view({{ news.pk }})" id="myImg" src="{{ news.picture.url }}" class="height-200 width-200 photo-fit-mobile round-edges news-counter" alt="item image"></a>
                            </div>
                        </div>
                    </div>
                    <div class="text-box text-box-mobile col-md-9 text-justify">
                        <div class="row">
                            <span><strong>Title: </strong>{{news.title}}</span>
                        </div>
                        <div class="row">
                            {% if news.description|length > 320 %}
                                <span><strong>Description: </strong>{{news.description|slice:"0:320"}}...</span>
                            {% else %}
                                <span><strong>Description: </strong>{{news.description}}</span>
                            {% endif %}
                        </div>
                        <div class="row">
                            <span><strong>Date: </strong>{{news.date}}</span>
                        </div>
                    </div>
                </div>
        {% endfor %}
    </div>
    {% else %}
        There no news!
    {% endif %}
{% endblock %}

templates/videos.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    Videos
{% endblock %}

{% block main %}
     <div class="text-center margin-top-50 mb-3">
        <h2 class="text-info dresscode-font">Hit Play!</h2>
    </div>
    <br>
    <div class="container margin-top-20">

    {% if video_articles %}
           {% for video in video_articles %}
                <div class="row margin-top-10 justify-content-center">
                    <div class="text-box text-box-mobile col-md-8">
                        <div class="row">
                            <span><strong>Title: </strong>{{video.title}}</span>
                        </div>
                        <div class="row">
                            <span><strong>Description: </strong>{{video.description}}</span>
                        </div>
                        </br>
                        <div class="row justify-content-center">
                            <iframe id="{{ video.pk }}" width="700" height="300" src="{{video.url}}?enablejsapi=1" frameborder="0"
                                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            {% endfor %}
    </div>
    {% else %}
        There no videos!
    {% endif %}

{% endblock %}